config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from datascience.apps import DatascienceConfig

from users.models import CustomUser


admin.site.site_header = "Control Panel"
admin.site.site_title = 'EZ Control Panel'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("datascience/", include("datascience.urls", namespace="datascience")),
    path("", include("pages.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    ] + urlpatterns

datascience/urls.py
from django.urls import path

from datascience.apps import DatascienceConfig
from datascience.views import *

from datascience.api.autocomplete import *

from datascience.api.drf_views import *

app_name = DatascienceConfig.name


urlpatterns = [
    # API CALLS
    # RESTFUL ENDPOINTS
    # CATEGORY
    path(
        "w101_droprate/category",
        W101CategoryListView.as_view(),
        name="w101_droprate_category_list",
    ),
    path(
        "w101_droprate/category/autocomplete",
        W101CategoryAutocompleteView.as_view(),
        name="w101_droprate_category_autocomplete",
    ),
    path(
        "w101_droprate/category/<int:pk>",
        W101CategoryDetailView.as_view(),
        name="w101_droprate_category_detail",
    ),
    # ITEM
    path(
        "w101_droprate/item",
        W101ItemListView.as_view(),
        name="w101_droprate_item_source_list",
    ),
    path(
        "w101_droprate/item/autocomplete",
        W101ItemAutocompleteView.as_view(),
        name="w101_droprate_item_autocomplete",
    ),
    path(
        "w101_droprate/item/<int:pk>",
        W101ItemDetailView.as_view(),
        name="w101_droprate_item_source_detail",
    ),
    # ITEM SOURCE
    path(
        "w101_droprate/item_source",
        W101ItemSourceListView.as_view(),
        name="w101_droprate_item_source_list",
    ),
    path(
        "w101_droprate/item_source/autocomplete",
        W101ItemSourceAutocompleteView.as_view(),
        name="w101_droprate_item_source_category_autocomplete",
    ),
    path(
        "w101_droprate/item_source/<int:pk>",
        W101ItemSourceDetailView.as_view(),
        name="w101_droprate_item_source_detail",
    ),
    # DROP ATTEMPT
    path(
        "w101_droprate/drop_attempt",
        W101DropAttemptListView.as_view(),
        name="w101_droprate_drop_attempt_list",
    ),
    path(
        "w101_droprate/drop_attempt/<int:pk>",
        W101DropAttemptDetailView.as_view(),
        name="w101_droprate_drop_attempt_detail",
    ),
    path(
        "w101_droprate/drop_attempt/form",
        W101DropAttemptEndpointView.as_view(),
        name="w101_droprate_drop_attempt_form",
    ),
    # BROWSER PAGES
    path(
        "w101_droprate/",
        W101DropRateDashboardView.as_view(),
        name="w101_droprate_dashboard",
    ),
    path("moderation/", ModerationView.as_view(), name="moderation_home"),
    path("", IndexView.as_view(), name="projects"),
]

pages/urls.py
from django.urls import path
from django.conf import settings

from .views import AppsPageView, BootstrapPageView, DRFIndexPageView, HomePageView, AboutPageView, ResumePageView, TestPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("apps/", AppsPageView.as_view(), name="apps_index"),
    path("resume/", ResumePageView.as_view(), name="resume"),
]

if settings.DEBUG:
    development_patterns = [
        path("test/", TestPageView.as_view(), name="test"),
        path("bootstrap/", BootstrapPageView.as_view(), name="bootstrap_index"),
        path("drf_index/", DRFIndexPageView.as_view(), name="drf_index"),
    ]
    urlpatterns.extend(development_patterns)

pages/templates/pages/about.html
{% extends '_base.html' %}

{% block content %}
<div class="mt-4 container container-mediumlike">
    <center>
        <h1>A Programmer is more than their Code</h1>
    </center>
    <h2>Ethics</h2>
    <p>
        Since high school I've struggled to understand how people are capable of doing things they know will cause harm
        to others. It's a stream of thought processes I'm simply incapable of
        understanding and I believe it is moving further and further to becoming the normal in modern day technology.
        <i>People are becoming second to profits.</i>
    </p>
    <p>
        It makes me feel sick.
    </p>
    <p>
        I want to be a force that fights to put people first in technology. This isn't difficult. As a programmer, I
        always follow the ACM ethics code and hope to contribute to the wider collective of developers that feel the
        same. It's everyone's responsibility to keep technology working for its users first, not just developers, but
        administration too.
    </p>
    <p>
        If you feel the same way or would like to see a professional's understanding of the problem, please feel free to
        check out <a href="https://blog.ethanzeigler.com">my blog.</a> I frequently share articles about computer
        science ethics that need to be more widely recognized and other interesting tidbits. On occasion, I'll write
        something myself, too.
    </p>
    <hr>
    <p>
        Now that <i>that's</i> out of the way...
    </p>
    <p>
        <h2>About Me</h2>
        Hiya! My name is Ethan Zeigler, and I'm a diagnosed psychop... <sub>Wait that's a different speech.*</sub> My
        name is Ethan Zeigler, and I am a software engineer and educator based in southern New Jersey. If you want to
        have a fun
        discussion with me or want me to show my passion for learning, ask about one of these things. You'll get a long
        and occasionally interesting rant. Oh, and learn more about my personality and who I am. You'll probably come to
        a conclusion fairly quick. It's some kind of mix between a happy puppy who is fascinated by just about
        everything, and a realist who wants to improve the world around him.
        <ul>
            <li>The physics and geometry behind bowling</li>
            <li>The internet of things (IOT) security nightmare waiting to happen</li>
            <li>How the Internet works on a technical level</li>
            <li>
                How cartoons are increasingly aimed at an adult audience despite their looks such as Steven Universe or
                Avatar
            </li>
            <li>The history behind our "throw away" culture</li>
            <li>How a CPU works internally and why I still can't believe it doesn't fail hundreds of times a second</li>
            <li>How our brains perceive color and why color deficiency, better known as color blindness, happens</li>
            <li>Mindfulness and meditation</li>
            <li>Why old plastic yellows</li>
        </ul>
        I'm essentially a walking dictionary of random knowledge. HMU if you have an odd question.<br><br>
        <sup class="pt-3">* This is only a joke.</sup>
    </p>
    <h2>Skillset</h2>
    <p>
        Currently, I'm an expert at the Java language and very adept in python. However, I've been leaning more towards
        golang for my newer projects due to it's sheer simplicity and maintainability. Normally, my focus is on
        developing backend technology and middleware. I'm reasonably familiar with RDS and SQl, specifically Postgres,
        and have a strong understanding of concurrent and parallel processing. Writing performant code is so much fun
        to me and having it well documented is the cherry on top.
    </p>
    <p>
        There's no replacement for actual code examples though. In the footer below you'll find a github button. Please
        feel free to explore my work. Not all of it is up to my professional standards. My more serious works are pinned
        in my profile. It comes down to the amount of work in the project and it's usage beyond myself.
    </p>
    <p>Thanks for visiting my site!</p>
</div>
{% endblock content %}

pages/templates/pages/drf_index.html
{% extends '_base.html' %}

{% block content %}
  <ul>
    <li><a href="{% url 'datascience:w101_droprate_category_list' %}">Category List</a></li>
    <li><a href="{% url 'datascience:w101_droprate_category_autocomplete' %}">Category Autocomplete</a></li>
    {% comment %} <li><a href="{% url 'datascience:w101_droprate_category_detail' %}">Category Detail</a></li> {% endcomment %}

    <li><a href="{% url 'datascience:w101_droprate_item_source_list' %}">Item Source List</a></li>
    <li><a href="{% url 'datascience:w101_droprate_item_source_category_autocomplete' %}">Item Source's Category Autocomplete</a></li>
    {% comment %} <li><a href="{% url 'datascience:w101_droprate_item_source_detail' %}">Item Source Detail</a></li> {% endcomment %}

    <li><a href="{% url 'datascience:w101_droprate_drop_attempt_list' %}">Drop Attempt List</a></li>
    {% comment %} <li><a href="{% url 'datascience:w101_droprate_drop_attempt_detail' %}">Drop Attempt Detail</a></li> {% endcomment %}
    <li><a href="{% url 'datascience:w101_droprate_drop_attempt_form' %}">Drop Attempt Form</a></li>
  </ul>
{% endblock content %}

pages/templates/pages/home.html
{% extends '_base.html' %}

{% block navigation %}{% endblock navigation %}

{% block content %}

<!-- Header -->
  <header class="masthead-full d-flex">
    <div class="attribution"><a href="https://www.outdoorproject.com/users/tyson-gillard">img_attr:Tyson Gillard</a></div>
    <div class="container text-center my-auto">
      <h1 class="mb-1">Ethan Zeigler</h1>
      <h3 class="mb-5">
        <em>Software Solutions</em> for Real World Problems
      </h3>
      <div class="flex-container navigation-links">
        <a class="btn btn-primary btn-lg m-2 js-scroll-trigger disabled" href="https://calendar.google.com/calendar/embed?src=p6cvqb95rs0cmoh9o70narodpo%40group.calendar.google.com&ctz=America%2FNew_York">Tutoring Calendar</a>
        <a class="btn btn-primary btn-lg m-2 js-scroll-trigger" href="{% url 'datascience:projects' %}">Apps</a>
        <a class="btn btn-primary btn-lg m-2 js-scroll-trigger" href="https://blog.ethanzeigler.com/">Blog</a>
        <a class="btn btn-primary btn-lg m-2 js-scroll-trigger" href="{% url 'resume' %}">Resume</a>     
        <a class="btn btn-primary btn-lg m-2 js-scroll-trigger" href="{% url 'about' %}">About</a>
      </div>
    </div>
    <div class="overlay"></div>
  </header>

  <!-- About -->
  <section class="content-section bg-light" id="about">
    <div class="d-flex flex-wrap justify-content-center text-center align-items-center plain-section mx-auto">
      <div class="col logo-lg mb-5"></div>
      <div class="col-md">
        <h2>
          “Your work is going to fill a large part of your life, and the only way to be truly
          satisfied is to do what you believe is great work.” - <i>Jobs</i>
        </h2>
        <div class="mx-auto plain-section text-center">
          <p class="lead">This isn't here because its inspiring, but because it's how I do my work every day.</p>
          <p class="lead mb-0">A job done poorly is not truly done.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Services -->
  <section class="content-section pb-4 bg-primary text-white text-center" id="services">
    <div class="container">
      <div class="content-section-heading">
        <h3 class="text-secondary mb-0">Why me?</h3>
        <h2 class="mb-5">I'm More than my Code</h2>
      </div>
      <div class="row justify-content-sm-around">
        <div class="col-lg-3 col-md-6 mb-5 ">
          <span class="service-icon rounded-circle mx-auto mb-3">
            <i class="icon-check"></i>
          </span>
          <h4>
            <strong>Stakeholder First</strong>
          </h4>
          <p class="text-faded mb-0">Software, user interfaces, and performance should work <i>for</i> stakeholders, not against them</p>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
          <span class="service-icon rounded-circle mx-auto mb-3">
            <i class="icon-star"></i>
          </span>
          <h4>
            <strong>Enthusiastic</strong>
          </h4>
          <p class="text-faded mb-0">A project isn't just the product, but moreover a love for the work and its purpose</p>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
          <span class="service-icon rounded-circle mx-auto mb-3">
            <i class="icon-heart"></i>
          </span>
          <h4>
            <strong>Compassionate</strong>
          </h4>
          <p class="text-faded mb-0">A caring heart goes further and stronger through adversities than even a brilliant mind</p>
        </div>
        <div class="col-lg-3 col-md-6">
          <span class="service-icon rounded-circle mx-auto mb-3">
            <i class="icon-book-open"></i>
          </span>
          <h4>
            <strong>Scholarly</strong>
          </h4>
          <p class="text-faded mb-0">Learning for the sake of learning is not only fun, but the comes in handy more than one would think</p>
        </div>
        <div class="col-lg-3 col-md-6 mb-5 ">
          <span class="service-icon rounded-circle mx-auto mb-3">
            <i class="icon-present"></i>
          </span>
          <h4>
            <strong>Friendly</strong>
          </h4>
          <p class="text-faded mb-0">A happy and connected team has better health, less burnout, more fun, and makes better work</p>
        </div>
        <div class="col-lg-3 col-md-6 mb-5 ">
          <span class="service-icon rounded-circle mx-auto mb-3">
            <i class="icon-grid"></i>
          </span>
          <h4>
            <strong>Organized</strong>
          </h4>
          <p class="text-faded mb-0">Messy code makes me feel bad. Therefore, I <i>don't</i> write messy code. Usually. We're humans.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Callout
  <section class="callout">
    <div class="container text-center">
      <h2 class="mx-auto">Have an empty space on your canvas, or need to smooth out some edges?
        <em>Let's make something great together!</em>
      </h2>
      <a class="mb-0 btn btn-primary btn-xl" href="mailto:zeiglee1@tcnj.edu">Contact me!</a>
    </div>
  </section> -->

  <!-- Portfolio -->
  <section class="content-section" id="portfolio">
    <div class="container">
      <div class="content-section-heading text-center">
        <h3 class="text-secondary mb-0">Portfolio</h3>
        <h2 class="mb-5">Recent Projects</h2>
        <h5 class="mb-5">Whoops! This will soon automatically fill with projects and news, but it's a work in progress. Checkout my
          <a href="https://github.com/EthanZeigler">github</a> for the time being!
        </h5>
      </div>
      <div class="row no-gutters">
        <!--<div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Stationary</h2>
                <p class="mb-0">A yellow pencil with envelopes on a clean, blue backdrop!</p>
              </span>
            </span>
            <img class="img-fluid" src="img/portfolio-1.jpg" alt="">
          </a>
        </div>
        <div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Ice Cream</h2>
                <p class="mb-0">A dark blue background with a colored pencil, a clip, and a tiny ice cream cone!</p>
              </span>
            </span>
            <img class="img-fluid" src="img/portfolio-2.jpg" alt="">
          </a>
        </div>
        <div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Strawberries</h2>
                <p class="mb-0">Strawberries are such a tasty snack, especially with a little sugar on top!</p>
              </span>
            </span>
            <img class="img-fluid" src="img/portfolio-3.jpg" alt="">
          </a>
        </div>
        <div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Workspace</h2>
                <p class="mb-0">A yellow workspace with some scissors, pencils, and other objects.</p>
              </span>
            </span>
            <img class="img-fluid" src="img/portfolio-4.jpg" alt="">
          </a>
        </div>-->
      </div>
    </div>
  </section>

  <!-- Call to Action -->
  <section class="content-section bg-primary text-white">
    <div class="container text-center">
      <h2 class="mb-4">I share stuff! Want to listen?</h2>
      <h4 class="mb-4"><span class="text-faded">(git) <i>Check out my blog!</i></h4>
      <div class="mb-4 d-flex justify-content-center">
        <a href="https://blog.ethanzeigler.com" class="btn btn-lg btn-dark align-content-center mx-3">The Musings of a Software Engineer</a>
      </div>
      <h2 class="my-3 mt-5">Or peek at some social feeds</h4>
      <a class="twitter-timeline" data-width="500" data-height="500" data-dnt="true" href="https://twitter.com/zeigler_ethan?ref_src=twsrc%5Etfw">Tweets by zeigler_ethan</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></a>
    </div>
  </section>

{% endblock content %}

pages/templates/pages/resume.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
<div class="my-4 container">
  <h2 class="header">Resume Versions</h2>
  <div class="subheader mb-4">
    <h4><small>For privacy reasons, my full resume is hidden. If you have the code to view the full version, enter it on the right (or bottom, if on mobile)</small></h4>
  </div>
  <div class="d-flex flex-wrap">
    <div class="small card resume-card mr-5 mb-2">
      <img class="card-img-top" src="{% static 'images/portfolio/backgrounds/material-paper-simple.sm.jpg' %}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Basic</h5>
        <p class="card-text">Simple, internet-friendly version. No personal identifying information.</p>
        <a href="#" class="btn btn-primary btn-resume mt-auto disabled">Open</a>
        <span class="text-muted">Coming soon</span>
      </div>
    </div> 
    <div class="card resume-card mr-5">
      <img class="card-img-top" src={% static 'images/portfolio/backgrounds/material-paper-complex.sm.jpg' %} alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Full</h5>
        <p class="small card-text">Complete resume with contact information and other details that are not safe to be on the open internet. To view this, a codeword is needed that someone who has interacted with me in person will know. If you don't and you should, please ask me for it.</p>
        <div class="small input-group">
          <label for=full-resume-button><b>Codeword:</b> left side, 3rd line, 2nd word of business card + right side, 2nd line, 1st word letters 2-3</label>
          <button id="full-resume-btn" class="input-group-prepend btn btn-primary disabled btn-resume d-inline">Open</button>
          <input type="text" class="form-control d-inline" id="resume-codeword-input" placeholder="Codeword">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

pages/templates/pages/test.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Ethan Zeigler{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'images/core/favicons/favicon.ico' %}">
  {% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" integrity="sha256-7O1DfUu4pybYI7uAATw34eDrgQaWGOfMV/8erfDQz/Q=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- App scss start -->
    {% render_bundle 'global' 'css' %}
    {% render_bundle 'data_moderation' 'css' %}
    <!-- App scss end -->
  {% endblock %}
</head>
</body>
  <div class="position-absolute">
    <div id=alert-container class="alert-container sticky-top mx-1 pt-1">
      {% if messages %}
      <!-- Messages found -->
        {% for message in messages %}
          <!-- message: {{ message }} -->
          <div role="alert" class="alert alert-{{message.level_tag}} alert-dismissable fade show">
            {{ message.message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% else %}
        <!-- No messages from system -->
      {% endif %}
    </div>
  </div>


{% comment %} TESTING SPACE {% endcomment %}
<div id="moderation-app"></div>







{% comment %} / TESTING SPACE / {% endcomment %}




    <!-- Le javascript -->
  {% block javascript %}
    <!-- Global -->
    {% render_bundle 'global' 'js' %}
    {% render_bundle 'datascience' 'js' %}
  {% endblock javascript %}
</body>
</html>